# Generated by Django 4.2 on 2023-04-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Venue',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='venue',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='production',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='production',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='production',
            name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='lineup',
            field=models.ManyToManyField(to='gigs.artist'),
        ),
    ]
