# Generated by Django 4.2 on 2023-06-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_rename_location_venue_rename_start_time_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='contact_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
