# Generated by Django 4.2 on 2023-04-30 13:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_rename_location_venue_rename_start_time_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='contact_number',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
    ]
