# Generated by Django 4.2 on 2023-08-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_event_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='display_name',
            field=models.CharField(default='display', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
